---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server_hostname: 'infra1'                                   # str  - required, hostname of server
server_vm_fixed_addr: '10.0.2.100'                          # str  - not required, used to specify fixed address when using internal DHCPD
server_mac_address: '52:54:00:bd:80:00'                     # str  - required, mac address of default interface

server_networks:                        # dict - required, hash of networks, can be empty, key is used to name the networks.
  dhcp:
    iface: 'eth0'                       # str  - required, interface name
    inet_type: 'dhcp'                   # str  - required, iface type [static, dhcp, manual]
    vm_int_iface: vm-br-dhcp            # str  - not Required, used to specify an integration networks interface when provisioning a VM
  mgmt:
    iface: 'eth1'                       # str  - required, interface name
    inet_type: 'static'                 # str  - required, iface type [static, dhcp, manual]
    address: '10.0.236.100/22'          # str  - not required, must be in CIDR format
    vm_int_iface: vm-br-eth1            # str  - not Required, used to specify an integration networks interface when provisioning a VM
  flat:
    iface: 'eth2'                       # str  - required, interface name
    inet_type: 'static'                 # str  - required, iface type [static, dhcp, manual]
    address: '10.0.248.100/22'          # str  - not required, must be in CIDR format
    vm_int_iface: vm-br-eth2            # str  - not Required, used to specify an integration networks interface when provisioning a VM
  vlan:
    iface: 'eth3'                       # str  - required, interface name
    inet_type: 'manual'                 # str  - required, iface type [static, dhcp, manual]
    vm_int_iface: vm-br-eth3            # str  - not Required, used to specify an integration networks interface when provisioning a VM
  vxlan:
    iface: 'eth4'                       # str  - required, interface name
    inet_type: 'static'                 # str  - required, iface type [static, dhcp, manual]
    address: '10.0.240.100/22'          # str  - not required, must be in CIDR format
    vm_int_iface: vm-br-eth4            # str  - not Required, used to specify an integration networks interface when provisioning a VM
  storage:
    iface: 'eth5'                       # str  - required, interface name
    inet_type: 'static'                 # str  - required, iface type [static, dhcp, manual]
    address: '10.0.244.100/22'          # str  - not required, must be in CIDR format
    vm_int_iface: vm-br-eth5            # str  - not Required, used to specify an integration networks interface when provisioning a VM
